name: docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - web/template/**
      - mkdocs.yml
      - requirements.txt
      - .github/workflows/docs.yml
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - web/template/**
      - mkdocs.yml
      - requirements.txt
      - .github/workflows/docs.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure Python runtime
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build documentation
        run: mkdocs build

      - name: Upload static bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: public


  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: docs
      url: https://mykil.io
    steps:
      - name: Download static bundle
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: public

      - name: Configure documentation domain
        run: echo $DOMAIN > public/CNAME
        env:
          DOMAIN: ${{ secrets.DOMAIN }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: docs
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
