name: ecad

on:
  push:
    paths:
      - "ecad/**"
      - ".github/workflows/ecad.yml"
  pull_request:
    paths:
      - "ecad/**"
      - ".github/workflows/ecad.yml"
  workflow_dispatch:

jobs:
  fabrication:
    strategy:
      matrix:
        pcb:
          - cremini-blade-atmega328p
          - cremini-backplane-lm2596
          - mushroom-backplane-dm28
          - mushroom-backplane-tps54560
          - mushroom-backplane-tps54561
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create output directory
        run: mkdir -p build

      - name: Generate fabrication files
        uses: nerdyscout/kicad-exports@v2.2
        with:
          config: ecad/jlcpcb.kibot.yml
          dir: build
          board: ecad/${{ matrix.pcb }}/${{ matrix.pcb }}.kicad_pcb
          schema: ecad/${{ matrix.pcb }}/${{ matrix.pcb }}.sch

      - name: Create gerber file archive
        uses: montudor/action-zip@v1
        with:
          args: zip -jr build/upload/gerber.zip build/gerber

      - name: Upload fabrication files
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.pcb }}
          path: build/upload/*

      - name: Update alpha release artifacts
        uses: ncipollo/release-action@v1
        if: ${{ github.ref == 'refs/heads/main' }} # only on main branch
        with:
          artifacts: "build/upload/*"
          tag: main
          allowUpdates: true
          omitBody: true
          omitName: true
          token: ${{ secrets.GITHUB_TOKEN }}
